### ISSUE TITLE
Come up with a better name

### ISSUE THREAD

**Issue by Bauke** [Bauke/href-plus#1]
I'm bad at names so if you have any better ideas let me know. Ideally it should be pretty short and unique, potentially with a good TLD still available (I admit it's a hard ask).

**Comment by huffstler** [comment]
Keeping in mind that it's 1am for me now, I have a couple that might be okay?

- Song Share
- Disc.Discovery
- Rosetta Note
- LP.link
- EP Everywhere (or just extended.play ?)

**Comment by Bauke** [comment]
I like the Rosetta Stone reference, haha.

A shame .share isn't a TLD, song.share/link.share/music.share would all be pretty cool.

One I thought of just now was Song Gallery, the song.gallery domain is also still available.

**Comment by huffstler** [comment]
Did a little more looking up this morning, there's apparently a `.music` tld, might be worth a quick brainstorm as well.

**Comment by Bauke** [comment]
It's a proposed TLD but you can't register them right now as they're [in contention](https://icannwiki.org/.music) between a bunch of different companies.

**Comment by Bauke** [comment]
Thoughts on href+ / href.plus? Domain is still available and I kinda like it.

**Comment by silverhook** [comment]
audiohref.plus ?
